apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: deploy_view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy_view_rule
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: deploy_view
