apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: deploy_edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy_edit_rule
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: deploy_edit
