apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sa-namespace-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-namespace-admin_rule
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
  namespace: default
