apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: empty
  name: empty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: empty
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empty
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        volumeMounts:
          - name: empty
            mountPath: /empty
      volumes:
        - name: empty
          emptyDir: {}
status: {}